import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import '../styles/globals.css';
import { Provider } from '@/components/ui/provider';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import '@smastrom/react-rating/style.css';

// DM Sans fontni ulash
const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={dmSans.variable}>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
